services:
  owpanel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: owpanel
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - panel-data:/opt/owpanel/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/nginx:/etc/nginx
      - /www:/www
    environment:
      - OWPANEL_PORT=8888
      - OWPANEL_DATA=/opt/owpanel/data
    privileged: true

volumes:
  panel-data:
